In [26]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [138]:

import os, sys
repo_root = os.path.abspath("..")
src_path = os.path.join(repo_root, "src")

import pandas as pd
import datetime as dt
import numpy as np
#import matplotlib.pyplot as plt
#import seaborn as sns
import datetime as dt
from scipy.stats import skew, kurtosis, shapiro
#plt.style.use(['bmh'])
import talib
#from pandas_datareader import data as pdr
import yfinance as yfin
#yfin.pdr_override()
import yaml
from utils import utils, telebot

In [139]:
all_config = yaml.safe_load(open("../config_file.yml", "r"))

In [29]:
df_input = utils.get_ticks_data('../src/data/example_data.csv')

In [30]:
start_date, end_date = utils.get_start_end(all_config)
source = all_config['stocks']['source']
metric = all_config['stocks']['metric']
ticks = df_input['TICK'].to_list()

In [31]:
df = utils.get_stock_data(ticks, start_date, end_date, col=metric)

In [32]:
print("Following ticks will be analyzed: \n %s" % df.columns)

Following ticks will be analyzed:
 Index(['AAPL', 'ACN', 'AXP', 'BA', 'BABA', 'BRK-B', 'CSCO', 'DIS', 'EGP',
       'GOOGL', 'HD', 'INTC', 'JPM', 'KO', 'MA', 'MCD', 'META', 'MSFT', 'MU',
       'NEE', 'NFLX', 'NKE', 'NVDA', 'PEP', 'PG', 'SBUX', 'SUI', 'TMUS', 'UNH',
       'V'],
      dtype='str', name='Ticker')

In [39]:
df_clean = utils.get_metrics(df, all_config['model']['kpis'])

In [40]:
df_clean

,price,stock,rsi,bb_low,bb_mid,bb_up,ema_low,ema_up
2025-03-07,238.032562,AAPL,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-10,226.492844,AAPL,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-11,219.881653,AAPL,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-12,216.038406,AAPL,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-13,208.770081,AAPL,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2026-02-23,306.519989,V,33.083871,330.681136,324.390207,318.099278,320.46314,325.551742
2026-02-24,307.220001,V,33.894669,330.61793,323.360507,316.103084,318.425734,324.193835
2026-02-25,312.98999,V,40.314252,330.372276,322.780473,315.188671,317.589466,323.36392
2026-02-26,316.700012,V,44.074905,329.957236,322.300117,314.642999,317.452627,322.870298
2026-02-27,320.140015,V,47.385205,329.145613,321.751259,314.356904,317.866071,322.668054

In [41]:
dflags = utils.get_flags(df_clean, all_config['strategy'])

In [43]:
dflags.head()

,price,stock,rsi,bb_low,bb_mid,bb_up,ema_low,ema_up,rsi_f,bb_f,ema_f,score
2026-02-27,308.899994,AXP,31.312952,357.815365,343.597501,329.379636,333.74532,344.089852,1,1,1,3
2026-02-27,144.110001,BABA,29.966987,164.504941,157.977499,151.450056,153.468504,157.355157,1,1,1,3

# Telegram
1. Create a bot, a Telegram chat group and add the bot on it
2. Add the bot by using /my_id @<bot name> 
3. get the chat id

In [147]:
token = all_config['bot']['chat_token']
chat_id = all_config['bot']['chat_id']

In [148]:
bot = telebot.Tabot(token, chat_id)

In [149]:
print(type(bot))

<class 'utils.telebot.Tabot'>

In [150]:
bot.chat_id

492441228

In [151]:
bot.get_chat_id()

In [152]:
ur = 'https://api.telegram.org/bot' + bot.chat_token + '/getUpdates'
print(ur)

https://api.telegram.org/bot5325333941:AAHf4xLPRuTqSoTkYZGqtPw4U1sN_OiaaeU/getUpdates

In [153]:
 bot.chat_token,

('5325333941:AAHf4xLPRuTqSoTkYZGqtPw4U1sN_OiaaeU',)

In [154]:
bot.check_bot()

<Response [200]>

### Sending the msg

In [155]:
total_ticks = len(df.columns)
msg_ticks = len(dflags.stock)

In [156]:
total_ticks

30

In [157]:
msg_title = "Stocks KPIs for {end_date}: \nWe got {msg_ticks} possible ticks from {total_ticks} \n".format(end_date=end_date, msg_ticks=msg_ticks,total_ticks=total_ticks)
msg_header = '\nTICK \t PRICE RSI RSI_F BB_F EMA_F FLAGS\n'

In [158]:
msgs = []
for row in dflags.itertuples():
    msgs.append('{s}   \t {p}\t {rsi} {rsi_f} {bb_f} {ema_f} {score} \n'.\
                format(s=row.stock, p=np.round(row.price,1), rsi=np.round(row.rsi, 1), rsi_f=row.rsi_f,bb_f= row.bb_f, ema_f=row.ema_f, score= row.score))

msg_formated = ' '.join(msgs)

In [159]:
message = msg_title + msg_header + msg_formated

In [160]:
message

'Stocks KPIs for 2026-03-02: \nWe got 2 possible ticks from 30 \n\nTICK \t PRICE RSI RSI_F BB_F EMA_F FLAGS\nAXP   \t 308.9\t 31.3 1 1 1 3 \n BABA   \t 144.1\t 30.0 1 1 1 3 \n'

In [161]:
bot.send_message(message)

### Pending

In [ ]:
df_test = df['AAPL']

In [ ]:
talib.RSI(df_test).plot(figsize=(20,5))

In [ ]:
df_test.plot(figsize=(20,8))

In [ ]:
upper_1sd, mid_1sd, lower_1sd = talib.BBANDS(df['APPL'], 
                                     nbdevup=1,
                                     nbdevdn=1,
                                     timeperiod=20)
# Plot the upper and lower Bollinger Bands 
plt.figure(figsize=(20,8))
plt.plot(df['APPL'], color='green', label='Price')
plt.plot(upper_1sd, color='tomato', label="Upper 1sd")
plt.plot(lower_1sd, color='tomato', label='Lower 2sd')

# Customize and show the plot
plt.legend(loc='upper left')
plt.title('Bollinger Bands (1sd)')
plt.show()